### ISSUE TITLE
Attaching to remote VM

### ISSUE THREAD

**Issue by sskorol** [odnoklassniki/jvm-serviceability-examples#1]
Hi,

Playing with VM attach API. Local usage is pretty straightforward.
But I'm wondering, how can I connect to jsadebugd using VirtualMachine.attach?

Noticed that I can get a list of connected remote JVMs via MonitoredHost activeVms() API. But it requires jstatd running. Does it mean that I need to start both jstatd and jsadebugd on target remote VM? If yes, how can I do that? How can I reuse single rmiregistry for both tools?

I'm new to this topic. Would be greatly appreciated if you point me what I'm missing.

Thanks,
Sergey

**Comment by apangin** [comment]
Hi,

You cannot attach to a remote JVM using Dynamic Attach Mechanism (at least with built-in APIs).

jsadebugd is a different thing - it is a Serviceability Agent proxy. It binds to a particular Java process or coredump and allows you to use SA tools remotely

**Comment by sskorol** [comment]
@apangin thanks! In such case what would you recommend to use for getting remoteDataDump and heapHisto from remote JVM? Or it's better to create some http trigger to do it locally first and then just send results to requester? I'm curious about a better way of remote JVM monitoring, as you have a huge experience working with these tools.

**Comment by apangin** [comment]
I guess the easiest way is just to invoke ssh command, but HTTP proxy will also do. It's easy to implement such on your own: remoteDataDump() returns InputStream, you just need to trasfer stream data to the client.

**Comment by sskorol** [comment]
Sounds feasible, thanks! Will try this approach.
